language:
    python
python:
    - "3.4"
    - "3.4.1"
    - "3.4.2"
    - "3.4.3"

# command to install dependencies
install: 
    - "pip install -r requirement/requirements.txt"

# command to run tests
script:
    - pep8 .
